query($slug:String!) {
  profile: findProfileBySlug(slug: $slug) {
    about
    ...user
    posts (first: 20) {
      nodes {
        author { ...user}
        createdAt
        content
        id
        comments (first: 5) {
          nodes {
          	...comment
            replies (first: 5) {
              nodes {
                ...comment
              }
            }
          }
        }
      }
    }
  }
}

fragment user on Profile {
  name
  slug
  id
  url
  avatarImage {
    views {
      name,
      url
    }
  }
}

fragment comment on Comment {
  id
	author {
	  ...user
	}
	createdAt
	content
	likes (first: 10) {
	 	totalCount
	}
}