name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: kitsu-io-build
        path: build/**
  deploy-alpha:
    runs-on: self-hosted

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.6
        with:
          name: kitsu-io-build
          path: build
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: build 
          TARGET: ${{ secrets.REMOTE_TARGET }}
